# Generated by Django 6.0.7 on 2026-07-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro')], default='usd', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('items', models.ManyToManyField(related_name='orders', to='app.item')),
            ],
        ),
    ]
