# Generated by Django 6.0.7 on 2026-07-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_item_currency_remove_item_price_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('item', 'currency')},
        ),
    ]
